# The simplest possible configuration for Just the Docs

remote_theme: just-the-docs/just-the-docs

# Enable search
search_enabled: true

# Site settings
title: Data Archiving 101
description: A guide to data archiving at NOAA PIFSC.
